### ISSUE TITLE
Could rdinstret be moved to the c code?

### ISSUE THREAD

**Issue by camel-cdr** [edre/rvv-chacha-poly#7]
vpoly.s currently calls rdinstret by it self.

rdinstret may not always be available, e.g. disabeled by the kernel, so it would be nice if the implementation could be more seperated from the measurements.

I wasn't able to find any external use of this code that relies on it's return value. On the contrary, https://github.com/OpenXiangShan/rvv-bench, currently advises to remove the instruction manually.

**Comment by edre** [comment]
The rdinstret used in the middle of the assembly file is for computing how much time the function spends in the precomputation phase. Since the real hardware benchmarks are measuring cycles not instructions, I don't have a problem with just deleting that functionality.

**Comment by camel-cdr** [comment]
Sory, I forgot about this. It's probably not worth changing.
